# Generated by Django 3.0.5 on 2020-06-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
